# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HackathonThing' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'

pod "MDCSwipeToChoose"
pod 'SVProgressHUD'
end

target 'HackathonThingTests' do

end

target 'HackathonThingUITests' do

end

